
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("ProjectONE", "music", 10000, 010120, 01052020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("ProjectTWO", "math", 15000, 020120, 020520);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("ProjectTHREE", "art", 12000, 030120, 030520);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("ProjectFOUR", "social studies", 10000, 040120, 040520);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("ProjectFIVE", "Theater", 20000, 050120, 050520);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("ProjectSIX", "science", 18000, 060120, 060520);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("ProjectSEVEN", "sports", 13000, 070120, 070520);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("ProjectEIGHT", "media", 25000, 080120, 080520);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("ProjectNINE", "history", 5000, 090120, 090520);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("ProjectTEN", "criminal justice", 17000, 100120, 100520);

INSERT INTO users (name, age) VALUES ("John", 27);
INSERT INTO users (name, age) VALUES ("Jacob", 23);
INSERT INTO users (name, age) VALUES ("Jingle", 25);
INSERT INTO users (name, age) VALUES ("Heimer", 13);
INSERT INTO users (name, age) VALUES ("Smith", 19);
INSERT INTO users (name, age) VALUES ("His", 17);
INSERT INTO users (name, age) VALUES ("Name", 19);
INSERT INTO users (name, age) VALUES ("Is", 32);
INSERT INTO users (name, age) VALUES ("My", 45);
INSERT INTO users (name, age) VALUES ("Nombre", 50);
INSERT INTO users (name, age) VALUES ("Too", 33);
INSERT INTO users (name, age) VALUES ("Whenever", 12);
INSERT INTO users (name, age) VALUES ("We", 25);
INSERT INTO users (name, age) VALUES ("Go", 56);
INSERT INTO users (name, age) VALUES ("Out", 66);
INSERT INTO users (name, age) VALUES ("The", 77);
INSERT INTO users (name, age) VALUES ("People", 39);
INSERT INTO users (name, age) VALUES ("Always", 20);
INSERT INTO users (name, age) VALUES ("Shout", 47);
INSERT INTO users (name, age) VALUES ("Hisname", 90);

INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 2, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4000, 4, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6000, 7, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 9, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 10, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 12, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (7000, 13, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (8000, 14, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 15, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12, 16, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4000, 17, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (11000, 18, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (120, 19, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 20, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 17, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 13, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9000, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 12, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 4, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 3, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 7, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 18, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4000, 19, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6000, 15, 7);
